palette = "catppuccin_mocha"

format = """
[░▒▓](surface1)\
[ $os ](bg:surface2 fg:text)\
[](bg:overlay0 fg:surface2)\
$directory\
[](fg:overlay0 bg:overlay1)\
$git_branch\
$git_status\
[](fg:overlay1 bg:overlay2)\
$nodejs\
$rust\
$golang\
$php\
[](fg:overlay2 bg:base)\
$time\
[ ](fg:base)\
\n$character"""

[directory]
style = "fg:#e3e5e5 bg:overlay0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:overlay1"
format = '[[ $symbol $branch ](fg:overlay0 bg:overlay1)]($style)'

[git_status]
style = "bg:overlay1"
format = '[[($all_status$ahead_behind )](fg:overlay0 bg:overlay1)]($style)'

[nodejs]
symbol = ""
style = "bg:overlay2"
format = '[[ $symbol ($version) ](fg:overlay0 bg:overlay2)]($style)'

[rust]
symbol = ""
style = "bg:overlay2"
format = '[[ $symbol ($version) ](fg:overlay0 bg:overlay2)]($style)'

[golang]
symbol = ""
style = "bg:overlay2"
format = '[[ $symbol ($version) ](fg:overlay0 bg:overlay2)]($style)'

[php]
symbol = ""
style = "bg:overlay2"
format = '[[ $symbol ($version) ](fg:overlay0 bg:overlay2)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'

[character]
success_symbol = "[❯](bold green)"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[os]
disabled = false
style = "bg:surface2 fg:text"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""